# -*- coding: utf-8 -*-
"""Visibility_Boost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkwuGzPMHcBWq1OGhKNKoC0jBPTfMqq0
"""

# --- Dehazing via Dark Channel Prior (He et al., 2009) ---
# Works in Google Colab. Save as one cell and run.

import numpy as np, cv2, os
from pathlib import Path


def box_min_filter(img, r):
    """Fast min filter via erosion (structuring element is (2r+1)x(2r+1))."""
    k = 2*r + 1
    return cv2.erode(img, np.ones((k, k), np.uint8))

def dark_channel(I, r):
    """
    Dark channel: min over color channels, then local min in a (2r+1)x(2r+1) patch.
    I is uint8 BGR image.
    """
    # min over channels
    min_per_pixel = I.min(axis=2)
    # local min
    dark = box_min_filter(min_per_pixel, r)
    return dark

def estimate_atmospheric_light(I, dark, top_percent=0.001):
    """
    Atmospheric light A from top 0.1% brightest pixels in dark channel,
    then pick the pixel with highest intensity in I among them.
    """
    h, w = dark.shape
    n_pixels = h * w
    n_search = max(1, int(n_pixels * top_percent))

    # Flatten and get indices of top dark values (most haze-opaque)
    flat_dark = dark.reshape(-1)
    idx = np.argpartition(flat_dark, -n_search)[-n_search:]
    # Among those, pick the location with largest I sum (brightest in the input)
    I_flat = I.reshape(-1, 3)
    brightest_idx = idx[np.argmax(I_flat[idx].sum(axis=1))]
    A = I_flat[brightest_idx].astype(np.float32)  # BGR
    return A

def estimate_transmission(I, A, r, omega=0.95):
    """
    Transmission t~(x) = 1 - omega * min_y min_c ( I_c(y)/A_c ) over local patch.
    """
    # Normalize image by A (per channel)
    norm = np.empty_like(I, dtype=np.float32)
    for c in range(3):
        norm[..., c] = I[..., c].astype(np.float32) / max(A[c], 1e-6)

    # Per-pixel min across channels
    min_per_pixel = norm.min(axis=2)
    # Local min
    min_local = box_min_filter(min_per_pixel, r)
    t_est = 1.0 - omega * min_local
    return np.clip(t_est, 0.0, 1.0)

def guided_filter(guide_gray, src, r=40, eps=1e-3):
    """
    Lightweight guided filter (edge-preserving smoothing).
    guide_gray: float32 [0,1], src: float32 [0,1]
    """
    # Mean filters
    kernel = (2*r+1, 2*r+1)
    mean_I  = cv2.boxFilter(guide_gray, ddepth=-1, ksize=kernel, normalize=True)
    mean_p  = cv2.boxFilter(src,        ddepth=-1, ksize=kernel, normalize=True)
    mean_Ip = cv2.boxFilter(guide_gray*src, ddepth=-1, ksize=kernel, normalize=True)

    cov_Ip = mean_Ip - mean_I*mean_p
    mean_II = cv2.boxFilter(guide_gray*guide_gray, ddepth=-1, ksize=kernel, normalize=True)
    var_I   = mean_II - mean_I*mean_I

    a = cov_Ip / (var_I + eps)
    b = mean_p - a*mean_I

    mean_a = cv2.boxFilter(a, ddepth=-1, ksize=kernel, normalize=True)
    mean_b = cv2.boxFilter(b, ddepth=-1, ksize=kernel, normalize=True)

    q = mean_a*guide_gray + mean_b
    return q

def recover_radiance(I, t, A, t0=0.1):
    """
    J(x) = (I(x)-A)/max(t(x), t0) + A
    """
    t = np.clip(t, t0, 1.0).astype(np.float32)
    J = np.empty_like(I, dtype=np.float32)
    for c in range(3):
        J[..., c] = (I[..., c].astype(np.float32) - A[c]) / t + A[c]
    return np.clip(J, 0, 255).astype(np.uint8)

def dehaze_image_bgr(I_bgr,
                     patch_radius=7,   # (2r+1)≈15 as in the paper
                     omega=0.95,
                     t0=0.1,
                     refine=True,
                     gf_radius=40,
                     gf_eps=1e-3):
    """
    Full pipeline:
      1) Dark channel
      2) A estimation
      3) Transmission estimation
      4) (Optional) guided-filter refinement (paper used soft matting)
      5) Radiance recovery
    """
    dark = dark_channel(I_bgr, r=patch_radius)
    A = estimate_atmospheric_light(I_bgr, dark, top_percent=0.001)
    t_est = estimate_transmission(I_bgr, A, r=patch_radius, omega=omega)

    if refine:
        # Guided filter using the gray input as guide to preserve edges
        guide = cv2.cvtColor(I_bgr, cv2.COLOR_BGR2GRAY).astype(np.float32) / 255.0
        t_ref = guided_filter(guide, t_est.astype(np.float32), r=gf_radius, eps=gf_eps)
        t = np.clip(t_ref, 0.0, 1.0)
    else:
        t = t_est

    J = recover_radiance(I_bgr, t, A, t0=t0)
    return J, t, A, dark

# Single image test
# ----------------------------
INPUT_IMG = "/content/test.png"
out_img   = "/content/your_hazy_image_dehazed-4.jpg"

I = cv2.imread(INPUT_IMG, cv2.IMREAD_COLOR)
J, t, A, dark = dehaze_image_bgr(I, patch_radius=7, omega=0.95, t0=0.1, refine=True)
cv2.imwrite(out_img, J, [cv2.IMWRITE_JPEG_QUALITY, 95])

